### ISSUE TITLE
Weird VERSION.txt

### ISSUE THREAD

**Issue by arnested** [reload/deployotron#49]
Something let to a weird `VERSION.txt`. Haven't investigated whether this is an old git or something else.

```yaml
Deployment info
---------------
Tags: error: unknown option `points-at', usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>],    or: git tag -d <tagname>...,    or: git tag -l [-n[<num>]] [<pattern>],    or: git tag -v <tagname>..., ,     -l                    list tag names,     -n[<n>]               print <n> lines of each tag message,     -d                    delete tags,     -v                    verify tags, , Tag creation options,     -a                    annotated tag, needs a message,     -m <msg>              message for the tag,     -F <FILE>             message in a file,     -s                    annotated and GPG-signed tag,     -u <key-id>           use another key to sign the tag,     -f, --force           replace the tag if exists, , Tag listing options,     --contains <commit>   print only tags that contain the commit,
SHA: 2a0383e0f6ef5d180097befd57c9dc1bf6f672b1
Time of deployment: Thu, 08 Dec 2016 15:07:54 +0100
Deployer: www-deploy@tst-kb-dru1
```
